INSERT INTO list (exercise_name) VALUES ('Bench Press (Barbell)');
INSERT INTO list (exercise_name) VALUES ('Bent Over Row (Dumbbell)');
INSERT INTO list (exercise_name) VALUES ('Bicep Curl (Barbell)');
INSERT INTO list (exercise_name) VALUES ('Bicep Curl (Dumbbell)');
INSERT INTO list (exercise_name) VALUES ('Bicep Curl (barbell )');
INSERT INTO list (exercise_name) VALUES ('Cable Fly');
INSERT INTO list (exercise_name) VALUES ('Chin Up');
INSERT INTO list (exercise_name) VALUES ('Curl Dumbbell');
INSERT INTO list (exercise_name) VALUES ('Cycling');
INSERT INTO list (exercise_name) VALUES ('Deadlift');
INSERT INTO list (exercise_name) VALUES ('Deadlift (Barbell)');
INSERT INTO list (exercise_name) VALUES ('Deadlift - Trap Bar');
INSERT INTO list (exercise_name) VALUES ('Face pull');
INSERT INTO list (exercise_name) VALUES ('Front Raise (Dumbbell)');
INSERT INTO list (exercise_name) VALUES ('Front Squat (Barbell)');
INSERT INTO list (exercise_name) VALUES ('Glute extension. ');
INSERT INTO list (exercise_name) VALUES ('Good Morning');
INSERT INTO list (exercise_name) VALUES ('Good Morning (Barbell)');
INSERT INTO list (exercise_name) VALUES ('Hack Squat');
INSERT INTO list (exercise_name) VALUES ('Hammer Curl');
INSERT INTO list (exercise_name) VALUES ('Hammer Curl (Dumbbell )');
INSERT INTO list (exercise_name) VALUES ('Hammer Decline Chest Press');
INSERT INTO list (exercise_name) VALUES ('Hammer High Row - 1 Arm');
INSERT INTO list (exercise_name) VALUES ('Hammer Row - Wide Grip');
INSERT INTO list (exercise_name) VALUES ('Hammer Row Stand 1armed');
INSERT INTO list (exercise_name) VALUES ('Hammer back row wide 45 angle');
INSERT INTO list (exercise_name) VALUES ('Hammer lat pulldown');
INSERT INTO list (exercise_name) VALUES ('Hammer seated row');
INSERT INTO list (exercise_name) VALUES ('Hammer seated row (CLOSE GRIP)');
INSERT INTO list (exercise_name) VALUES ('Hammer shoulder press');
INSERT INTO list (exercise_name) VALUES ('Incline Bench Press');
INSERT INTO list (exercise_name) VALUES ('Incline Bench Press (Barbell)');
INSERT INTO list (exercise_name) VALUES ('Incline Press (Dumbbell)');
INSERT INTO list (exercise_name) VALUES ('Landmine Press');
INSERT INTO list (exercise_name) VALUES ('Lat Pulldown');
INSERT INTO list (exercise_name) VALUES ('Lat Pulldown ');
INSERT INTO list (exercise_name) VALUES ('Lat Pulldown (Cable)');
INSERT INTO list (exercise_name) VALUES ('Lat Pulldown Closegrip');
INSERT INTO list (exercise_name) VALUES ('Lateral Raise');
INSERT INTO list (exercise_name) VALUES ('Lateral Raise (Dumbbell)');
INSERT INTO list (exercise_name) VALUES ('Lateral Raise (Dumbbells)');
INSERT INTO list (exercise_name) VALUES ('Leg Extension (Machine)');
INSERT INTO list (exercise_name) VALUES ('Leg curl');
INSERT INTO list (exercise_name) VALUES ('Leg outward fly');
INSERT INTO list (exercise_name) VALUES ('Leg press');
INSERT INTO list (exercise_name) VALUES ('Leg press (hinge )');
INSERT INTO list (exercise_name) VALUES ('Low Incline Dumbbell Bench');
INSERT INTO list (exercise_name) VALUES ('Military Press (Standing)');
INSERT INTO list (exercise_name) VALUES ('Neutral Chin');
INSERT INTO list (exercise_name) VALUES ('Overhead Press (Barbell)');
INSERT INTO list (exercise_name) VALUES ('Overhead Press (Dumbbell)');
INSERT INTO list (exercise_name) VALUES ('Pull Up');
INSERT INTO list (exercise_name) VALUES ('Rack Pull - 1 Pin');
INSERT INTO list (exercise_name) VALUES ('Rack Pull 2 Pin');
INSERT INTO list (exercise_name) VALUES ('Rear delt fly');
INSERT INTO list (exercise_name) VALUES ('Romanian Deadlift (Barbell)');
INSERT INTO list (exercise_name) VALUES ('Rope Never Ending ');
INSERT INTO list (exercise_name) VALUES ('Rotator cuff work. ');
INSERT INTO list (exercise_name) VALUES ('Seated Cable Row (close Grip)');
INSERT INTO list (exercise_name) VALUES ('Seated Military Press');
INSERT INTO list (exercise_name) VALUES ('Seated Military Press (Dumbbell)');
INSERT INTO list (exercise_name) VALUES ('Seated Row');
INSERT INTO list (exercise_name) VALUES ('Seated Shoulder  Press (Barbell)');
INSERT INTO list (exercise_name) VALUES ('Seated Shoulder Press (Dumbbell)');
INSERT INTO list (exercise_name) VALUES ('Shoulder Press (Standing)');
INSERT INTO list (exercise_name) VALUES ('Shrugs');
INSERT INTO list (exercise_name) VALUES ('Shrugs (dumbbell)');
INSERT INTO list (exercise_name) VALUES ('Skullcrusher (Barbell)');
INSERT INTO list (exercise_name) VALUES ('Sling Shot Bench');
INSERT INTO list (exercise_name) VALUES ('Sling Shot Incline');
INSERT INTO list (exercise_name) VALUES ('Squat');
INSERT INTO list (exercise_name) VALUES ('Squat (Barbell)');
INSERT INTO list (exercise_name) VALUES ('Stairmaster');
INSERT INTO list (exercise_name) VALUES ('T-bar Row');
INSERT INTO list (exercise_name) VALUES ('Tricep Extension');
INSERT INTO list (exercise_name) VALUES ('Tricep pushdown');
INSERT INTO list (exercise_name) VALUES ('Weighted dips');
INSERT INTO list (exercise_name) VALUES ('close grip Bench');
INSERT INTO list (exercise_name) VALUES ('curl ez bar');
INSERT INTO list (exercise_name) VALUES ('high bar squat');
INSERT INTO list (exercise_name) VALUES ('kettlebell Swings');
INSERT INTO list (exercise_name) VALUES ('lying Skullcrusher');
INSERT INTO list (exercise_name) VALUES ('sumo deadlift');